runmode: debug             # 开发模式，debug，release，test
port: :6663                # HTTP 绑定端口
name: apiservice           # API Service 名字
url: http://127.0.0.1:6663 # pingService 函数请求的 API 服务器的 ip:prot
max_ping_count: 10         # pingService 函数尝试的次数